= Jakarta Concurrency TCK Reference Guide
:author: Kyle Aure
:email: cu-dev@eclipse.org
:revnumber: v1.2
:toc:
:sectnums:

:APIShortName: Concurrency
:APILongName: Jakarta Concurrency
:APIVersion: 3.2

:APISpecSite: https://jakarta.ee/specifications/concurrency/3.2/
:APIEclipseSite: https://projects.eclipse.org/projects/ee4j.cu
:APIGitSite: https://github.com/jakartaee/concurrency

:TCKTestPlatform: Junit5
:SigPluginVersion: 2.3
:SigPluginGAV: jakarta.tck:sigtest-maven-plugin:{SigPluginVersion}

:JavaVersion1: 21
:JavaVersion2: 25

:license: Eclipse Foundation Technology Compatibility Kit License
:licenseURL: https://www.eclipse.org/legal/tck.php

:TCKProcess: Jakarta EE TCK Process
:TCKProcessURL: https://jakarta.ee/committees/specification/tckprocess/

:last-update-label!:

== Preface

This guide describes how to download, install, configure, and run the Technology Compatibility Kit (TCK) used to verify the compatibility of an implementation of the {APILongName} specification.  

The specification describes the job specification language, Java programming model, and runtime environment for {APILongName} applications.

=== Licensing

The {APILongName} TCK is provided under the {licenseURL}[*{license}*].

=== Who Should Use This Guide

This guide will assist in running the test suite, which verifies implementation compatibility for:

* implementers of {APILongName}. 

=== Terminology - "SE mode" vs. "EE mode"

Building on the previous point, it is convenient to use, as shorthand, the term "EE mode" when talking about the TCK constructs and requirements specifically for users running the TCK to certify against the entire EE platform. It is a convenient shorthand term too, then, to use the term "SE mode" for users that are only trying to certify against the {APILongName} specification, though this term in some ways might be misleading.  

Some specifications have a subset of tests that can run in "SE mode" without the requirement of running against an entire EE Platform.  The {APIShortName} TCK, however, runs all tests in "EE mode" and will require a Jakarta EE platform to test against.

=== Terminology - "Standalone TCK"

The community will sometimes refer to this TCK as the "standalone" {APIShortName} TCK.  This usage comes from the fact that {APILongName} is part of the Jakarta EE Platform, which has a platform-level TCK, which we're distinguishing this "standalone" TCK from.  

This terminology is confusing, since readers might interpret "standalone" to mean that this TCK can be run in SE Mode, when in-fact, it must be run in EE Mode. A better term would be `Specification TCK`, but that terminology is not yet being used. 

=== Terminology - "Test Client" vs "Test Server"

The {APIShortName} TCK acts as a `Test Client` that will install test applications onto a Jakarta EE Platform Server.
The Platform Server will act as a `Test Server` and run tests based on incoming requests from the `Test Client`.
Assertions will occur both on the client and server sides.

=== Before You Read This Guide

Before reading this guide, you should familiarize yourself with the {APILongName} Version {APIVersion} specification, which can be found at {APISpecSite}.

Other useful information and links can be found on the eclipse.org project home page for the {APILongName} project [{APIEclipseSite}] and also at the GitHub repository home for the specification project [{APIGitSite}].

== Major TCK Changes

This version of the {APILongName} TCK introduces two major changes to the TCK:

1. We change the official execution of the standalone TCK from Ant to Maven. Though the TCK has long been built with Maven and we even have included execution or "runner" Maven modules, our official documentation described an Ant-based execution.  This updated version of the TCK Reference Guide details the requirements and procedures for performing an official Maven-based execution of this TCK.
1. We changed from using a proprietary "Test Harness" framework to deploy and test applications on Jakarta EE Platforms, to using the open source Arquillian test framework.  

== What Tests Must I Pass To Certify Compatibility? 

=== Runtime Tests and Signature Tests Required

To certify compatibility with the entire Jakarta EE Platform (including {APILongName}), you will need to run the TCK against your implementation and pass 100% of both the:

* {TCKTestPlatform} runtime tests
* Signature tests

The two types of tests are encapsulated in a single execution or configuration.  This means that the Signature Tests will run alongside all other tests and no additional execution or configuration is required.

By "runtime" tests we simply mean tests simulating {APILongName} applications running against the {APIShortName} implementation attempting to certify compatibility.  These tests verify that the {APIShortName} applications behave according to the details defined in the specification, as validated by the TCK test logic.

=== Java SE level - Java {JavaVersion1} or Java {JavaVersion2}

The JDK used during test execution must be noted and listed as an important component of the certification request.   In particular, the Java SE version is important to note, and this version must be used consistently throughout both the {TCKTestPlatform} runtime and Signature tests for a given certification request.   

For the current TCK version, this can be done with either Java SE Version {JavaVersion1} or Version {JavaVersion2}.

== Prerequisites

=== Software To Install

1. **Java/JDK** - Install the JDK you intend to use for this certification request (Java SE Version {JavaVersion1} or Version {JavaVersion2}).  
1. **Maven** - Install Apache Maven 3.6.0 or higher.
1. **Jakarta EE Platform** - Jakarta EE Application Server or Container [Glassfish, Open Liberty, JBoss, WebLogic, etc.]

=== Testing Framework
To better understand how this TCK works, knowing what testing frameworks are being utilized is helpful.
Knowledge of how these frameworks operate and interact will help during the project setup.

1. **Arquillian** - Since the EE Platform TCK uses Arquillian to execute tests within an Arquillian "container" for certifying against the EE Platform, you must configure an Arquillian https://arquillian.org/guides/developing_a_container_adapter/[adapter] for your target runtime. Version 1.6.0 or later
1. **Signature Test Tool** - No action is needed here, but we note that the signature files were built and should be validated with the Maven plugin with group:artifact:version coordinates: **{SigPluginGAV}**, as used by the sample sigtest runner included in the TCK zip. This is a more specific direction than in earlier releases, in which it was left more open for the user to use a compatible tool.  Since there are small differences in the various signature test tools, we standardize on this version.

== A Guide to the TCK Distribution

This section explains how to obtain the TCK and extract it on your system.

=== Obtaining the Software

The {APILongName} TCK is distributed as a zip file, which contains the TCK artifacts (the test suite binary and source, porting package SPI binary and source, the test suite XML definitions, and signature files) in
`/artifacts`, the documentation in `/doc`, and a starter project in `/starter`.
You can access the current source code from the Git repository: {APIGitSite}.

=== The TCK Environment

The software can simply be extracted from the ZIP file.
Once the TCK is extracted, you'll see the following structure:

[source, txt]
----
concurrency-tck-<version>-dist/
  artifacts/
  docs/
  starter/
  LICENSE
  README.md
----

In more detail:

- `artifacts` contains all the test artifacts pertaining to the TCK: The TCK test classes and source, the {TCKTestPlatform} configuration file, a copy of the SignatureTest file for reference, and a script to copy the TCK into local maven repository.

- `docs` contains the documentation for the TCK: this reference guide.

- `starter` a very basic starter maven project to get you started.


=== A Quick Tour of the TCK Artifacts

==== What is included

The {APIShortName} TCK is a test library that includes four types of packages:

- `ee.jakarta.tck.concurrent.api.*` these are basic API tests that ensure methods throw the correct exceptions and return the valid values.
- `ee.jakarta.tck.concurrent.spec.*` these are more complex SPEC tests that ensure that implementations behave as expected based on the specification.
- `ee.jakarta.tck.concurrent.common.*` these are common packages shared between test packages.
- `ee.jakarta.tck.concurrent.framework` this package is an abstraction layer to make writing tests using {TCKTestPlatform}, Arquillian, SigTest, and java.util.logging easier.

===== API Signature Files

The one signature file exists for both Java {JavaVersion1} and {JavaVersion2}:

1. `artifacts/jakarta.enterprise.concurrent.sig`

**Note:** This signature file is for reference only.  A copy of the signature file is included in the {APIShortName} TCK test jar. 

==== What is not included
The {APIShortName} TCK uses but does not provide the necessary application servers, test frameworks, APIs, SPIs, or implementations required to run. 
It is up to the tester to include those dependencies and set up a test project to run the TCK.

Here is an essential checklist of what you will need, and links to the section that describe how to satisfy these requirements:

- An Application Server to test against | <<Software To Install>>
- The {APIShortName} API, {APIShortName} TCK, Arquillian, and {TCKTestPlatform} libraries available to the `Test Client` | <<Test Client Dependencies>>
- The Arquillian, {TCKTestPlatform}, Derby JDBC, and Signature Test libraries available to the `Test Server` | <<Test Server Dependencies>>
- An Arquillian SPI implementation for your Application Server | <<Configure Arquillian>>
- An Application Server configuration with specific security roles | <<Configure Application Server>>
- A logging configuration for TCK logging on `Test Client` and `Test Server` | <<Configure Logging>>

== TCK Test Requirements

Because there is flexibility regarding how a user could use Maven to configure a TCK execution, we make a separate, clear note here of the required number of tests needed to be passed in order to claim compliance via this TCK.

=== Runtime tests

For the {TCKTestPlatform} runtime tests of the TCK, 
the following table shows the number of tests that should pass based on platform: 

include::generated/runtime-tests.adoc[]

**Note:** Counts include signature test, but do not include disabled tests.

== Example runner

This section is dedicated to listing example runners for other implementations to use as a reference on how to configure and use the {APIShortName} TCK. 

Below are links to projects where the {APIShortName} TCK is being used and run successfully: 

* **Open Liberty**: https://github.com/OpenLiberty/open-liberty/tree/release/dev/io.openliberty.jakarta.concurrency.3.0_fat_tck

== Set up a TCK runner project

A simple maven project is required to control the lifecycle of the {APIShortName} TCK.

=== Test Client Dependencies

The entry point to running the TCK will be on the client-side using {TCKTestPlatform}. 
The Test Client will need to be configured with the dependencies necessary to run the TCK.
Some of these dependencies will depend on the application server you are using, and 
comments have been added to this sample describing the customizations necessary.

Example starter/pom.xml:

[source, xml]
----
include::../starter/pom.xml[tag=testClientDep]
----

Each of these Arquillian tests run within the runtime's Servlet container, with the help of an Arquillian adapter for that runtime implementation (mentioned as a prerequisite).

=== Test Server Dependencies

If the Test Server is running on a separate JVM (recommended), then the Test Server
will also need access to the {TCKTestPlatform}, Signature Test, and the Derby JDBC libraries.
The Test Server dependencies can be copied over during the build phase.

Example starter/pom.xml:

[source, xml]
----
include::../starter/pom.xml[tag=testServerDep]
----

Using the maven command:

[source, sh]
----
$ mvn dependency:copy
----

=== Configure {TCKTestPlatform}

{TCKTestPlatform} needs to be configured to know which Jakarta EE profile to test against.

In order for your maven project to execute these tests the surefire plugin needs to be configured.

Example starter/pom.xml: 

[source, xml]
----
include::../starter/pom.xml[tags=configSurefire;!arquillian;!logging]
----

=== Configure Arquillian

Application Servers that implement the Arquillian SPI use a configuration file to define properties, such as hostname, port, username, password, etc. These properties will allow Arquillian to connect to the application server, install applications, and get test responses. An Arquillian configuration file has been provided in the `starter/` directory. 

=== Configure Application Server

The {APIShortName} TCK uses default objects (`java:comp/DefaultManagedExecutorService`) and annotation-based configurations (`@ManagedExecutorDefinition`) 
to ensure that application servers require minimal customization to run the TCK.

However, the {APIShortName} TCK does require that Application Servers define a security context for security-based tests. 

- Username: javajoe
- Password: javajoe
- Group: Manager

The TCK uses external libraries that also need to be available on the Application Server's class path. 

- org.apache.derby:derby - For database testing
- org.junit.jupiter:junit-jupiter - For test assertions
- jakarta.tck:sigtest-maven-plugin - For signature testing

See <<Test Server Dependencies>>

=== Configure Logging

The {APIShortName} TCK uses `java.util.logging` for logging debug messages, and to output test results in some cases. 
Registered loggers exist both on the Test Client and Test Server meaning you will need to configure both sides to enable logging.
This is done by pointing the JVM to the logging configuration file using the property.
An example logging configuration file has been provided under the `/starter` directory. 

To enable logging for the Client side of tests, add a system property to the surefire plugin:

Example starter/pom.xml: 

[source, xml]
----
include::../starter/pom.xml[tag=logging]
----

To enable logging for the Server side of tests, set the same system property on the JVM running your application server.

=== Advanced Configuration

Some application servers may have custom deployment descriptors that they would like to include 
as part of the applications that are being deployed to their server. 
The custom deployment descriptors can be included in a programmatic way using ShrinkWrap and the Arquillian SPI.

Example ApplicationArchiveProcessor:

[source, java]
----
public class MyApplicationArchiveProcessor implements ApplicationArchiveProcessor {
    List<String> appNames;

    @Override
    public void process(Archive<?> archive, TestClass testClass) {
        if(appNames.contains(archive.getName())){
            ((WebArchive) archive).addAsWebInfResource("my-custom-sun-web.xml", "sun-web.xml");
        }
    }
----

Example LoadableExtension:

[source, java]
----
public class MyLoadableExtension implements LoadableExtension {
    @Override
    public void register(ExtensionBuilder extensionBuilder) {
        extensionBuilder.service(ApplicationArchiveProcessor.class, MyApplicationArchiveProcessor.class);
    }
}
----

Example META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension:

[source, txt]
----
my.custom.test.package.MyLoadableExtension
----

=== Test property reference

In the previous sections, there were sample configurations that contained information about
the different system properties that can be set under the `<systemPropertyVariables>` of the Surefire plugin. 

This section contains a complete list of the system properties that will be looked up by the TCK
and a short description of what data each represents. 

Use this reference as a quick guide for customizing how this TCK is run for your implementation.

include::generated/test-properties.adoc[]

Note: All non-java properties set on the test client will be exported to the test server, so there is no
need to set the same properties on both.

== Running the TCK

Once the TCK Runner project is created and configured the {APIShortName} TCK is run as part of the maven test lifecycle. 

[source, sh]
----
$ cd starter
$ mvn clean test
----


=== Expected Output

Here is example output when the starter runner runs successfully in full mode:

include::generated/expected-output.adoc[]

== Signature Tests

The signature tests validate the integrity of the `jakarta.enterprise.concurrent` Java "namespace" (or "package prefix") of the {APIShortName} implementation.   This would be especially important for an implementation packaging its own API JAR in which the API must be validated in its entirety.  For implementations expecting their users to rely on the API released by the {APILongName} specification project (e.g. to Maven Central) the signature tests are also important to validate that improper (non-spec-defined) extensions have not been added to `jakarta.enterprise.concurrent.*` packages/classes/etc.

=== Running signature tests

The {APIShortName} TCK will run signature tests on the application server itself, and not as part of a separate plugin / execution.
This means that the signature tests will run during the maven `test` phase.

The signature test plugin we use will also attempt to perform reflective access of classes, methods, and fields.
Due to the new module system in JDK 9+ special permissions need to be added in order for these tests to run: 

If you are using a Security Manager add the following permissions to applications running on your application server:

[source, txt]
----
permission java.lang.RuntimePermission "accessClassInPackage.jdk.internal";
permission java.lang.RuntimePermission "accessClassInPackage.jdk.internal.reflect";
permission java.lang.RuntimePermission "accessClassInPackage.jdk.internal.vm.annotation";
----

By default the java.base module only exposes certain classes for reflective access. 
Therefore, the {APIShortName} TCK test will need access to the `jdk.internal.vm.annotation` class.
To give the TCK access to this class set the following JVM properties: 

[source, properties]
----
--add-exports java.base/jdk.internal.vm.annotation=ALL-UNNAMED
--add-opens java.base/jdk.internal.vm.annotation=ALL-UNNAMED
----

Some JDKs will mistake the space in the prior JVM properties as delimiters between properties
In this case use:

[source, properties]
----
--add-exports=java.base/jdk.internal.vm.annotation=ALL-UNNAMED
--add-opens=java.base/jdk.internal.vm.annotation=ALL-UNNAMED
----

For more information about generating the signature test file, and how the test run read: [ee.jakarta.tck.concurrent.framework.signaturetest/README.md](https://github.com/jakartaee/concurrency/blob/master/tck/src/main/java/ee/jakarta/tck/concurrent/framework/signaturetest/README.md)

As mentioned in the prerequisite section the signature file formats across the various signature test tools have diverged and this test suite uses the Maven plugin with group:artifact:version coordinates: **{SigPluginGAV}**.

=== Expected output

The the Signature Test plugin will log output to `System.out`.  Whereas, the Signature Test framework we use to set up the test will log using `java.util.logging` so you may see these logs output to two separate locations depending on your application server. 

include::generated/expected-sig-output.adoc[]

== TCK Challenges/Appeals Process

The {TCKProcessURL}[{TCKProcess}] will govern all process details used for challenges to the {APILongName} TCK.

Except from the *{TCKProcess}*:

> Specifications are the sole source of truth and considered overruling to the TCK in all senses. In the course of implementing a specification and attempting to pass the TCK, implementations may come to the conclusion that one or more tests or assertions do not conform to the specification, and therefore MUST be excluded from the certification requirements.

> Requests for tests to be excluded are referred to as Challenges. This section identifies who can make challenges to the TCK, what challenges to the TCK may be submitted, how these challenges are submitted, how and to whom challenges are addressed.

=== Filing a Challenge 

The challenge process is defined within the [underline]#Challenges# section within the *{TCKProcess}*.

Challenges will be tracked via the {APIGitSite}/issues[issues] of the {APILongName} Specification repository.

The challenge process mentioned in the *{TCKProcess}* can be started by clicking {APIGitSite}/issues/new?assignees=&labels=challenge&projects=&template=tck-challenge.yml&title=TCK+Challenge[here],
it is recommended that you read through the challenge process to understand it in detail.

=== Successful Challenges

The following tests are exempt from TCK testing due to challenges:

include::generated/successful-challenges.adoc[]

== Certification of Compatibility

The {TCKProcessURL}[{TCKProcess}] will define the core process details used to certify compatibility with the {APILongName} specification, through execution of the {APILongName} TCK.

Except from the *{TCKProcess}*:

> Jakarta EE is a self-certification ecosystem.
If you wish to have your implementation listed on the official https://jakarta.ee implementations page for the given specification, a certification request as defined in this section is required.

=== Filing a Certification Request

The certification of compatibility process is defined within the [underline]#Certification of Compatibility# section within the *{TCKProcess}*.

Certifications will be tracked via the {APIGitSite}/issues[issues] of the {APILongName} Specification repository.

The certification of compatibility process mentioned in the *{TCKProcess}* can be started by clicking {APIGitSite}/issues/new?assignees=&labels=certification&projects=&template=certification.yml&title=Certification[here],
it is recommended that you read through the certification process to understand it in detail.

== Rules for {APILongName} Products

The following rules apply for each version of an operating system, software component,
and hardware platform Documented as supporting the Product:

- **Concurrency1** The Product must be able to satisfy all applicable compatibility requirements,
  including passing all Conformance Tests, in every Product Configuration and in every combination
  of Product Configurations, except only as specifically exempted by these Rules.
  For example, if a Product provides distinct Operating Modes to optimize performance,
  then that Product must satisfy all applicable compatibility requirements for a Product
  in each Product Configuration, and combination of Product Configurations, of those Operating Modes.

- **Concurrency1.1** If an Operating Mode controls a Resource necessary for the basic execution of the Test Suite,
  testing may always use a Product Configuration of that Operating Mode providing that Resource,
  even if other Product Configurations do not provide that Resource. Notwithstanding such exceptions,
  each Product must have at least one set of Product Configurations of such Operating Modes
  that is able to pass all the Conformance Tests.
  For example, a Product with an Operating Mode that controls a security policy (i.e., Security Resource)
  which has one or more Product Configurations that cause Conformance Tests to fail
  may be tested using a Product Configuration that allows all Conformance Tests to pass.

- **Concurrency1.2** A Product Configuration of an Operating Mode that causes the Product to report only
  version, usage, or diagnostic information is exempted from these compatibility rules.

- **Concurrency1.3** An API Definition Product is exempt from all functional testing requirements defined here,
  except the signature tests.

- **Concurrency2** Some Conformance Tests may have properties that may be changed.
  Properties that can be changed are identified in the configuration interview.
  Properties that can be changed are identified in the JavaTest Environment (.jte) files in the Test Suite installation.
  Apart from changing such properties and other allowed modifications described in this User's Guide (if any),
  no source or binary code for a Conformance Test may be altered in any way without prior written permission.
  Any such allowed alterations to the Conformance Tests will be provided via the Jakarta EE Specification Project website
  and apply to all vendor compatible implementations.

- **Concurrency3** The testing tools supplied as part of the Test Suite or as updated by the
  Maintenance Lead must be used to certify compliance.

- **Concurrency4** The Exclude List associated with the Test Suite cannot be modified.

- **Concurrency5** The Maintenance Lead can define exceptions to these Rules.
  Such exceptions would be made available as above, and will apply to all vendor implementations.

- **Concurrency6** All hardware and software component additions, deletions, and modifications to a
  Documented supporting hardware/software platform, that are not part of the Product but required
  for the Product to satisfy the compatibility requirements, must be Documented and available to users of the Product.
  For example, if a patch to a particular version of a supporting operating system is required for the
  Product to pass the Conformance Tests, that patch must be Documented and available to users of the Product.

- **Concurrency7** The Product must contain the full set of public and protected classes and interfaces
  for all the Libraries. Those classes and interfaces must contain exactly the set of public and
  protected methods, constructors, and fields defined by the Specifications for those Libraries.
  No subsetting, supersetting, or modifications of the public and protected API of the Libraries
  are allowed except only as specifically exempted by these Rules.

- **Concurrency7.1** If a Product includes Technologies in addition to the Technology Under Test,
  then it must contain the full set of combined public and protected classes and interfaces.
  The API of the Product must contain the union of the included Technologies.
  No further modifications to the APIs of the included Technologies are allowed.

- **Concurrency8** Except for tests specifically required by this TCK to be rebuilt (if any),
  the binary Conformance Tests supplied as part of the Test Suite or as updated by the
  Maintenance Lead must be used to certify compliance.

- **Concurrency9** The functional programmatic behavior of any binary class or interface must be
  that defined by the Specifications.

== Links

* {APILongName} TCK repository - {APIGitSite}
* {APILongName} specification/API repository - {APIGitSite}
* {APILongName} project home page - {APIEclipseSite}
* Arquillian and ShrinkWrap doc: https://arquillian.org/guides/shrinkwrap_introduction/
